In [2]:
import tensorflow as tf
import numpy as np
import sklearn as sk
from sklearn.datasets import make_classification
import scikitplot as skplt
import pandas as pd
import copy

In [3]:
landmarks_0 = pd.read_table("ribes_clement_266_annotations.csv",sep=",")
landmarks_1 = copy.copy(landmarks_0)
del landmarks_1['frame']
del landmarks_1['camera_facing_side']
landmarks_1

source  palm_root_x  palm_root_y  palm_thumb_1_x  \
0               open_palm.webm          541          389             458   
1               open_palm.webm          540          390             457   
2               open_palm.webm          540          390             456   
3               open_palm.webm          539          390             455   
4               open_palm.webm          539          390             454   
..                         ...          ...          ...             ...   
698  three_fingers_dorsal.webm            0            0               0   
699  three_fingers_dorsal.webm            0            0               0   
700  three_fingers_dorsal.webm            0            0               0   
701  three_fingers_dorsal.webm            0            0               0   
702  three_fingers_dorsal.webm            0            0               0   

     palm_thumb_1_y  palm_thumb_2_x  palm_thumb_2_y  palm_thumb_3_x  \
0               334             428             315             390   
1               334             427             315             390   
2               334             426             315             389   
3               334             426             314             389   
4               334             425             314             388   
..              ...             ...             ...             ...   
698               0               0               0               0   
699               0               0               0               0   
700               0               0               0               0   
701               0               0               0               0   
702               0               0               0               0   

     palm_thumb_3_y  palm_index_1_x  ...  dorsal_ring_4_x  dorsal_ring_4_y  \
0               288             468  ...                0                0   
1               288             468  ...                0                0   
2               288             468  ...                0                0   
3               288             467  ...                0                0   
4               288             467  ...                0                0   
..              ...             ...  ...              ...              ...   
698               0               0  ...                0                0   
699               0               0  ...                0                0   
700               0               0  ...                0                0   
701               0               0  ...                0                0   
702               0               0  ...                0                0   

     dorsal_pinky_1_x  dorsal_pinky_1_y  dorsal_pinky_2_x  dorsal_pinky_2_y  \
0                   0                 0                 0                 0   
1                   0                 0                 0                 0   
2                   0                 0                 0                 0   
3                   0                 0                 0                 0   
4                   0                 0                 0                 0   
..                ...               ...               ...               ...   
698               256               376               264               351   
699               254               376               262               350   
700               251               376               260               350   
701               249               376               258               350   
702               247               376               256               350   

     dorsal_pinky_3_x  dorsal_pinky_3_y  dorsal_pinky_4_x  dorsal_pinky_4_y  
0                   0                 0                 0                 0  
1                   0                 0                 0                 0  
2                   0                 0                 0                 0  
3                   0                 0                 0   

In [4]:
landmarks_2 = copy.copy(landmarks_1)
for i in range(len(landmarks_2)):
    label = landmarks_2.iloc[i]["source"]
    landmarks_2.at[i,'source'] = label[:-5]

In [5]:
landmarks_2

source  palm_root_x  palm_root_y  palm_thumb_1_x  \
0               open_palm          541          389             458   
1               open_palm          540          390             457   
2               open_palm          540          390             456   
3               open_palm          539          390             455   
4               open_palm          539          390             454   
..                    ...          ...          ...             ...   
698  three_fingers_dorsal            0            0               0   
699  three_fingers_dorsal            0            0               0   
700  three_fingers_dorsal            0            0               0   
701  three_fingers_dorsal            0            0               0   
702  three_fingers_dorsal            0            0               0   

     palm_thumb_1_y  palm_thumb_2_x  palm_thumb_2_y  palm_thumb_3_x  \
0               334             428             315             390   
1               334             427             315             390   
2               334             426             315             389   
3               334             426             314             389   
4               334             425             314             388   
..              ...             ...             ...             ...   
698               0               0               0               0   
699               0               0               0               0   
700               0               0               0               0   
701               0               0               0               0   
702               0               0               0               0   

     palm_thumb_3_y  palm_index_1_x  ...  dorsal_ring_4_x  dorsal_ring_4_y  \
0               288             468  ...                0                0   
1               288             468  ...                0                0   
2               288             468  ...                0                0   
3               288             467  ...                0                0   
4               288             467  ...                0                0   
..              ...             ...  ...              ...              ...   
698               0               0  ...                0                0   
699               0               0  ...                0                0   
700               0               0  ...                0                0   
701               0               0  ...                0                0   
702               0               0  ...                0                0   

     dorsal_pinky_1_x  dorsal_pinky_1_y  dorsal_pinky_2_x  dorsal_pinky_2_y  \
0                   0                 0                 0                 0   
1                   0                 0                 0                 0   
2                   0                 0                 0                 0   
3                   0                 0                 0                 0   
4                   0                 0                 0                 0   
..                ...               ...               ...               ...   
698               256               376               264               351   
699               254               376               262               350   
700               251               376               260               350   
701               249               376               258               350   
702               247               376               256               350   

     dorsal_pinky_3_x  dorsal_pinky_3_y  dorsal_pinky_4_x  dorsal_pinky_4_y  
0                   0                 0                 0                 0  
1                   0                 0                 0                 0  
2                   0                 0                 0                 0  
3                   0                 0                 0                 0  
4                   0                

In [6]:
landmarks_3 = copy.copy(landmarks_2)
classes = ["open_palm",
             "open_dorsal",
             "fist_palm",
             "fist_dorsal",
             "three_fingers_palm",
             "three_fingers_dorsal"]
for i in range(len(landmarks_3)):
    current_class = landmarks_3.at[i,'source']
    landmarks_3.at[i,'source'] = classes.index(current_class)
landmarks_3

source  palm_root_x  palm_root_y  palm_thumb_1_x  palm_thumb_1_y  \
0        0          541          389             458             334   
1        0          540          390             457             334   
2        0          540          390             456             334   
3        0          539          390             455             334   
4        0          539          390             454             334   
..     ...          ...          ...             ...             ...   
698      5            0            0               0               0   
699      5            0            0               0               0   
700      5            0            0               0               0   
701      5            0            0               0               0   
702      5            0            0               0               0   

     palm_thumb_2_x  palm_thumb_2_y  palm_thumb_3_x  palm_thumb_3_y  \
0               428             315             390             288   
1               427             315             390             288   
2               426             315             389             288   
3               426             314             389             288   
4               425             314             388             288   
..              ...             ...             ...             ...   
698               0               0               0               0   
699               0               0               0               0   
700               0               0               0               0   
701               0               0               0               0   
702               0               0               0               0   

     palm_index_1_x  ...  dorsal_ring_4_x  dorsal_ring_4_y  dorsal_pinky_1_x  \
0               468  ...                0                0                 0   
1               468  ...                0                0                 0   
2               468  ...                0                0                 0   
3               467  ...                0                0                 0   
4               467  ...                0                0                 0   
..              ...  ...              ...              ...               ...   
698               0  ...                0                0               256   
699               0  ...                0                0               254   
700               0  ...                0                0               251   
701               0  ...                0                0               249   
702               0  ...                0                0               247   

     dorsal_pinky_1_y  dorsal_pinky_2_x  dorsal_pinky_2_y  dorsal_pinky_3_x  \
0                   0                 0                 0                 0   
1                   0                 0                 0                 0   
2                   0                 0                 0                 0   
3                   0                 0                 0                 0   
4                   0                 0                 0                 0   
..                ...               ...               ...               ...   
698               376               264               351                 0   
699               376               262               350                 0   
700               376               260               350                 0   
701               376               258               350                 0   
702               376               256               350                 0   

     dorsal_pinky_3_y  dorsal_pinky_4_x  dorsal_pinky_4_y  
0                   0                 0                 0  
1                   0                 0                 0  
2                   0                 0                 0  
3                   0                 0                 0  
4                   0                 0                 0  
..              

In [7]:
landmarks_4 = landmarks_3.to_numpy(dtype=np.float32)
landmarks_4

array([[  0., 541., 389., ...,   0.,   0.,   0.],
       [  0., 540., 390., ...,   0.,   0.,   0.],
       [  0., 540., 390., ...,   0.,   0.,   0.],
       ...,
       [  5.,   0.,   0., ...,   0.,   0.,   0.],
       [  5.,   0.,   0., ...,   0.,   0.,   0.],
       [  5.,   0.,   0., ...,   0.,   0.,   0.]], dtype=float32)

In [53]:
landmarks_5 = np.copy(landmarks_4)
np.random.shuffle(landmarks_5)
landmarks_5[:700].shape

(700, 81)

In [67]:
X_train, X_test, Y_train, Y_test = landmarks_5[:600,1:], landmarks_5[600:700,1:], landmarks_5[:600,0], landmarks_5[600:700,0]

In [68]:
encoder = sk.preprocessing.OneHotEncoder(dtype=np.float32)
encoder.fit(Y_train.reshape((-1,1)))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float32'>,
              handle_unknown='error', sparse=True)

In [91]:
Y_train_encoded=encoder.transform(Y_train.reshape((-1,1))).toarray()
Y_test_encoded=encoder.transform(Y_test.reshape((-1,1))).toarray()
print(Y_test_encoded[:5])

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [79]:
train_dataset = tf.data.Dataset.from_tensor_slices((X_train,Y_train_encoded))
test_dataset = tf.data.Dataset.from_tensor_slices((X_test,Y_test_encoded))

In [80]:
# Group lines in batches
BATCH_SIZE = 50
train_dataset_batched = train_dataset.batch(BATCH_SIZE)
test_dataset_batched = test_dataset.batch(BATCH_SIZE)

In [81]:
# this snippet will dissapear at some point in the future
# it exists because I found two bugs in KerasClassifier while writing
# this notebook. 
# Issues are raised in the tensorflow repo and this should be fixed soon(TM)

from tensorflow.keras.wrappers.scikit_learn import KerasClassifier 

class KerasClassifier_Patched(KerasClassifier):
    # bugfix: classifier doesn't declare that it is a classifier
    # in the Scikit learn API
    _estimator_type = "classifier"
    
    # bugfix: the current wrapper does not work with HotOne encoded
    # labels
    # this is only a fix in the specific case of this notebook,
    # not a general one
    def score(self, x, y, **kwargs):
        _, accuracy = self.model.evaluate(x,y, verbose=0, **kwargs)
        return accuracy

In [93]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

def setupModel():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Input(shape=(80)))
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(6))
    model.add(tf.keras.layers.Softmax())
    model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1e-4),
                 loss=tf.keras.losses.CategoricalCrossentropy(),
                 metrics=[tf.keras.metrics.CategoricalAccuracy()])
    return model

mlp_model = KerasClassifier_Patched(build_fn=setupModel,
                               epochs=5,
                               batch_size=50,
                               verbose=0)

mlp_model.fit(X_train,Y_test_encoded)

ValueError: Input arrays should have the same number of samples as target arrays. Found 600 input samples and 100 target samples.